export const PLAYER_COMBAT_CONFIG = {
    maxHp: 100,
    baseDamage: 28,
    attackRange: 72,
    attackCooldown: 650,
    knockback: 260,
    projectileSpeed: 420,
    projectileLifetime: 650,
    buffDuration: 12000,
};

export const DROP_TABLES = {
    basic: [
        { itemId: 'coin', dropChance: 0.45, minAmount: 1, maxAmount: 3, rarity: 'common' },
        { itemId: 'health_potion', dropChance: 0.10, minAmount: 1, maxAmount: 1, rarity: 'uncommon' },
        { itemId: 'damage_buff', dropChance: 0.06, minAmount: 1, maxAmount: 1, rarity: 'uncommon' },
        { itemId: 'speed_buff', dropChance: 0.06, minAmount: 1, maxAmount: 1, rarity: 'uncommon' },
    ],
    elite: [
        { itemId: 'coin', dropChance: 0.85, minAmount: 5, maxAmount: 12, rarity: 'common' },
        { itemId: 'health_potion', dropChance: 0.22, minAmount: 1, maxAmount: 1, rarity: 'uncommon' },
        { itemId: 'damage_buff', dropChance: 0.18, minAmount: 1, maxAmount: 1, rarity: 'rare' },
        { itemId: 'attack_speed_buff', dropChance: 0.16, minAmount: 1, maxAmount: 1, rarity: 'rare' },
        { itemId: 'shield', dropChance: 0.16, minAmount: 1, maxAmount: 1, rarity: 'rare' },
        { itemId: 'rare_chest', dropChance: 0.10, minAmount: 1, maxAmount: 1, rarity: 'epic' },
    ],
    boss: [
        { itemId: 'coin', dropChance: 1, minAmount: 60, maxAmount: 90, rarity: 'common' },
        { itemId: 'rare_chest', dropChance: 1, minAmount: 1, maxAmount: 1, rarity: 'legendary' },
        { itemId: 'shield', dropChance: 0.70, minAmount: 1, maxAmount: 1, rarity: 'epic' },
    ],
};

export const ITEM_CONFIGS = {
    coin: { name: 'Coin', color: 0xf2c94c, scorePerAmount: 5 },
    health_potion: { name: 'Potion', color: 0xe74c3c, heal: 28 },
    damage_buff: { name: 'Damage', color: 0xff7a1a, damageMultiplier: 1.45 },
    speed_buff: { name: 'Speed', color: 0x2ecc71, speedMultiplier: 1.28 },
    attack_speed_buff: { name: 'Atk Speed', color: 0x56ccf2, cooldownMultiplier: 0.68 },
    shield: { name: 'Shield', color: 0x9bdbff, shield: 34 },
    rare_chest: { name: 'Chest', color: 0xb8752b, coinMin: 18, coinMax: 35 },
};

export const MONSTER_CONFIGS = {
    slime: {
        id: 'slime',
        name: 'Slime',
        type: 'basic',
        hp: 42,
        damage: 7,
        speed: 62,
        attackRange: 30,
        detectionRange: 320,
        attackCooldown: 1250,
        scoreValue: 40,
        dropTable: 'basic',
        assetKey: 'monster-slime',
        color: 0x63d471,
        radius: 15,
    },
    raider: {
        id: 'raider',
        name: 'Raider',
        type: 'fast',
        hp: 58,
        damage: 11,
        speed: 98,
        attackRange: 34,
        detectionRange: 420,
        attackCooldown: 950,
        scoreValue: 75,
        dropTable: 'basic',
        assetKey: 'monster-raider',
        color: 0xd97941,
        radius: 16,
    },
    brute: {
        id: 'brute',
        name: 'Brute',
        type: 'tank',
        hp: 150,
        damage: 20,
        speed: 48,
        attackRange: 42,
        detectionRange: 360,
        attackCooldown: 1500,
        scoreValue: 145,
        dropTable: 'basic',
        assetKey: 'monster-brute',
        color: 0x8e6fbe,
        radius: 23,
    },
    ranged: {
        id: 'ranged',
        name: 'Spitter',
        type: 'ranged',
        hp: 56,
        damage: 10,
        speed: 58,
        attackRange: 235,
        detectionRange: 440,
        attackCooldown: 1450,
        projectileSpeed: 230,
        scoreValue: 120,
        dropTable: 'basic',
        assetKey: 'monster-ranged',
        color: 0x7b61ff,
        radius: 16,
    },
    elite: {
        id: 'elite',
        name: 'Elite',
        type: 'elite',
        hp: 190,
        damage: 22,
        speed: 92,
        attackRange: 44,
        detectionRange: 520,
        attackCooldown: 1050,
        scoreValue: 300,
        dropTable: 'elite',
        assetKey: 'monster-elite',
        color: 0xf2c94c,
        radius: 24,
    },
    boss_warlord: {
        id: 'boss_warlord',
        name: 'Season Warlord',
        type: 'boss',
        hp: 1450,
        damage: 28,
        speed: 60,
        attackRange: 58,
        detectionRange: 900,
        attackCooldown: 950,
        scoreValue: 2500,
        dropTable: 'boss',
        assetKey: 'monster-boss-warlord',
        color: 0xc0392b,
        radius: 42,
    },
};

export const WAVE_CONFIGS = [
    { waveNumber: 1, durationSeconds: 180, spawnRate: 4200, maxEnemies: 8, monsterTypes: ['slime'], statMultiplier: 1, eliteChance: 0 },
    { waveNumber: 2, durationSeconds: 180, spawnRate: 3400, maxEnemies: 12, monsterTypes: ['slime', 'raider'], statMultiplier: 1.12, eliteChance: 0.03 },
    { waveNumber: 3, durationSeconds: 180, spawnRate: 2850, maxEnemies: 16, monsterTypes: ['slime', 'raider', 'ranged'], statMultiplier: 1.25, eliteChance: 0.07 },
    { waveNumber: 4, durationSeconds: 180, spawnRate: 2200, maxEnemies: 22, monsterTypes: ['raider', 'brute', 'ranged'], statMultiplier: 1.45, eliteChance: 0.16 },
    { waveNumber: 5, durationSeconds: 180, spawnRate: 1800, maxEnemies: 28, monsterTypes: ['slime', 'raider', 'brute', 'ranged'], statMultiplier: 1.65, eliteChance: 0.22, bossId: 'boss_warlord' },
];

export const SCORE_CONFIG = {
    waveClear: [0, 350, 650, 1000, 1500, 2500],
    survivalPointPerSecond: 2,
    bossKillBonus: 4000,
    runCompletionBonus: 6000,
    highHpBonusMultiplier: 18,
};

export const SEASON_CONFIG = {
    seasonId: 'season-alpha-001',
    startDate: '2026-06-01T00:00:00.000Z',
    endDate: '2026-07-01T00:00:00.000Z',
    rewardPool: 125000,
    feePercentage: 7.5,
    playerRank: 18,
    estimatedReward: 420,
    leaderboard: [
        { rank: 1, playerId: '0xAURORA', score: 98500, rewardShare: '25%' },
        { rank: 2, playerId: '0xEMBER', score: 86750, rewardShare: '15%' },
        { rank: 3, playerId: '0xVANTA', score: 81120, rewardShare: '10%' },
        { rank: 4, playerId: '0xNOVA', score: 76800, rewardShare: '3.57%' },
        { rank: 5, playerId: '0xLYRA', score: 74150, rewardShare: '3.57%' },
    ],
    rewardDistribution: [
        { ranks: '1', share: 25 },
        { ranks: '2', share: 15 },
        { ranks: '3', share: 10 },
        { ranks: '4-10', share: 25 },
        { ranks: '11-100', share: 25 },
    ],
};
